environment:
  nodejs_version: '14'
  # https://ci.appveyor.com/pricing 6-8 GiB? Using 5 GiB as max:
  NODE_OPTIONS: '--max-old-space-size=5120'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn --frozen-lockfile

test_script:
  - git --version
  - node --version
  - yarn --version
  - cd packages\vite && yarn build
  - cd packages\plugin-vue && yarn build
  - yarn test

cache:
  - node_modules -> yarn.lock

build: off
